#!/bin/zsh
echo "pakker pakker"
cd debs/unpacked/
dpkg-deb -b -Zgzip OS_X_Theme ../
dpkg-deb -b -Zgzip PetersTema ../
dpkg-deb -b -Zgzip White_BootLogo ../
dpkg-deb -b -Zgzip Peters_Respring_Logos ../
dpkg-deb -b -Zgzip StatusBarTheme ../
cd test
make package
mv packages/* ./../../
echo "pakker pakket"
